package timeconst

const NANO_PER_SECOND int64 = 1000000000
const SECONDS_PER_MINUTE = 60
const SECONDS_PER_HOUR = 3600

const MAX_HOUR = 23
const MAX_MINUTE = 59
const MAX_SECOND = 59
const MAX_NANO = 999_999_999

const HOURS_PER_DAY int64 = 24
const MINUTES_PER_HOUR = 60
const MINUTES_PER_DAY = HOURS_PER_DAY * MINUTES_PER_HOUR
const SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY

const NANOS_PER_MILLI = 1000_000
const NANOS_PER_SECOND = 1000_000_000

const NANOS_PER_MINUTE = NANOS_PER_SECOND * SECONDS_PER_MINUTE
const NANOS_PER_HOUR = NANOS_PER_MINUTE * MINUTES_PER_HOUR
const NANOS_PER_DAY = NANOS_PER_HOUR * HOURS_PER_DAY

const MILLIS_PER_DAY = SECONDS_PER_DAY * 1000
const MICROS_PER_DAY = SECONDS_PER_DAY * 1000_000
